name: CI
on:
  pull_request: 
    branches: [ main ]
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ Windows ]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Build product
        run: |
          bazel build :testrepo
